name: Validate JSONs and Donation files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check files in donations.yml
        uses: mikefarah/yq@v4.6.1
        with:
          cmd: set -e; ls -la */donations.yml; for F in */donations.yml; do yq e '.[].files' $F | cut -d' ' -f2 | while read PROOF; do echo -n $PROOF; [ ! -f "$PROOF" ] && echo ' does not exist' && exit; echo ' exists'; done; done

      - name: Create jsons out of donations.yml
        uses: mikefarah/yq@v4.6.1
        with:
          cmd: "for F in */donations.yml; do DEST=${F/yml/json}; yq -j e . $F > $DEST; cat $DEST; done"

      - name: The Validate JSON action insists of adding the pwd to all json paths, so lets trick it
        run: |
          mkdir -p /home/runner/work/Donations/Donations/home/runner/work/Donations/
          ln -s /home/runner/work/Donations/Donations /home/runner/work/Donations/Donations/home/runner/work/Donations/Donations
          ls -la  /home/runner/work/Donations/Donations/home/runner/work/Donations

      - name: Debug all donations.json files
        run: "for i in */donations.json; do echo $i; cat $i; echo; done"
      - name: Validate JSON
        uses: kiriakos/validate-json-action@e97bf4885314574701657ab73e5b7fceb3e07130
        with:
          schema: .github/schemas/donations-schema.json
        env:
          INPUT_SCHEMA: .github/schemas/donations-schema.json
          INPUT_JSONS: "/home/runner/work/Donations/Donations/*/donations.json"


